NasrullahKhan_SkillTest_Truckoom/Controllers/VehicleMaintenanceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NasrullahKhan_SkillTest_PenaltyCalculation.Class;
using System.Data;
using System.Data.SqlClient;

namespace NasrullahKhan_SkillTest_Truckoom.Controllers
{
    
    public class VehicleMaintenanceController : Controller
    {
        GeneralClass db = new GeneralClass();
        public IActionResult Index()
        {
            ViewBag.Vehicle = LoadVehicle();
            return View();
        }

        [HttpGet]
        public List<SelectListItem> LoadVehicle()
        {
            List<SelectListItem> lst = new List<SelectListItem>();
            lst.Add(new SelectListItem { Value = "0", Text = "--SELECT--" });

            try
            {
                SqlCommand sqlComm = new SqlCommand();
                sqlComm.CommandText = "SELECT VehicleID, CONCAT(MakeName, ' | ', ModelName, ' | ', Year, ' | ', LicensePlate) AS VehicleName \r\nFROM Vehicles A INNER JOIN MAKE B ON A.Make = B.MAKEID\r\nINNER JOIN MODELS C ON A.Model = C.MODELID AND B.MAKEID = C.MAKEID";
                DataTable dt = db.GetDataTable(sqlComm);

                foreach (DataRow dr in dt.Rows)
                {
                    lst.Add(new SelectListItem { Value = dr["VehicleID"].ToString(), Text = dr["VehicleName"].ToString().ToUpper() });
                }

                dt.Dispose();
            }
            catch (Exception ex)
            {

            }
            return lst;
        }

        [HttpGet]
        public IActionResult GetMaintenanceRecord()
        {
            try
            {
                SqlCommand sqlcomm = new SqlCommand();
                sqlcomm.CommandText = "SELECT MaintenanceID,MakeName,ModelName,Year,LicensePlate,MaintenanceType,FORMAT(MaintenanceDate,'dd-MMM-yyyy') as MaintenanceDate,\r\nDescription,Notes FROM MaintenanceActivities A INNER JOIN Vehicles B ON A.VehicleID = B.VehicleID\r\nINNER JOIN MAKE C ON B.Make = C.MAKEID\r\nINNER JOIN MODELS D ON B.Model = D.MODELID AND C.MAKEID = D.MAKEID";
                DataTable dt = db.GetDataTable(sqlcomm);
                if (dt.Rows.Count == 0)
                {
                    return Json(new { success = true, data = new List<object>() });
                }

                var records = dt.AsEnumerable().Select(row => new
                {
                    MaintenanceID = row.Field<int>("MaintenanceID"),
                    Make = row.Field<string>("MakeName"),
                    Model = row.Field<string>("ModelName"),
                    Year = row.Field<int>("Year"),
                    LicensePlate = row.Field<string>("LicensePlate"),
                    MaintenanceType = row.Field<string>("MaintenanceType"),
                    MaintenanceDate = row.Field<string>("MaintenanceDate"),
                    Description = row.Field<string>("Description"),
                    Notes = row.Field<string>("Notes"),
                }).ToList();

                return Json(new { success = true, data = records });
            }
            catch (Exception ex) {
                return StatusCode(500, new { success = false, message = "An error occurred", error = ex.Message });
            }

        }


        [HttpPost]
        public IActionResult SaveVehicleMaintenance(VehicleMaintenanceModel vmodel, bool IsEdit)
        {
            try
            {
                string validateData = isValidate(vmodel);
                if (validateData == null)
                {
                    if (IsEdit)
                    {
                        if (UpdateData(vmodel))
                        {
                            return Json(new { success = true, message = "Vehicle Maintenance created successfully." });
                        }
                    }
                    else
                    {
                        if (InsertData(vmodel))
                        {
                            return Json(new { success = true, message = "Vehicle Maintenance created successfully." });
                        }
                    }
                }
                else
                {
                    return StatusCode(500, validateData.ToString());
                }
                return StatusCode(500, "An error occurred while creating the vehicle.");
            }
            catch (Exception ex)
            {
                throw new Exception("Create() " + ex.Message);

            }
        }

        [HttpPost]
        private bool InsertData(VehicleMaintenanceModel model)
        {
            try
            {
                SqlCommand sqlcomm = new SqlCommand();
                sqlcomm.CommandText = @"INSERT INTO MaintenanceActivities(VehicleID, MaintenanceType, MaintenanceCost, MaintenanceDate, Description, Notes, IsCompleted)
                                        VALUES(@VehicleID, @MaintenanceType, @MaintenanceCost, @MaintenanceDate, @Description, @Notes, @IsCompleted)";
                sqlcomm.Parameters.AddWithValue("@VehicleID", model.VehicleID);
                sqlcomm.Parameters.AddWithValue("@MaintenanceType", model.MaintenanceType);
                sqlcomm.Parameters.AddWithValue("@MaintenanceCost", model.MaintenanceCost);
                sqlcomm.Parameters.AddWithValue("@MaintenanceDate", model.MaintenanceDate);
                sqlcomm.Parameters.AddWithValue("@Description", model.Description);
                sqlcomm.Parameters.AddWithValue("@Notes", model.Notes);
                sqlcomm.Parameters.AddWithValue("@IsCompleted", model.IsCompleted);
                db.ExecuteNonQuery(sqlcomm);
                sqlcomm.Parameters.Clear();
                return true;
            }
            catch (Exception ex)
            {
                throw new Exception("Create() " + ex.Message);
            }
        }

        [HttpPut]
        private bool UpdateData(VehicleMaintenanceModel model)
        {
            try
            {
                SqlCommand sqlcomm = new SqlCommand();
                sqlcomm.CommandText = @"UPDATE MaintenanceActivities SET VehicleID = @VehicleID,MaintenanceType = @MaintenanceType,
                                    MaintenanceCost = @MaintenanceCost,MaintenanceDate = @MaintenanceDate,Description = @Description,Notes = @Notes,IsCompleted = @IsCompleted
                                WHERE MaintenanceID = @MaintenanceID";

                sqlcomm.Parameters.AddWithValue("@VehicleID", model.VehicleID);
                sqlcomm.Parameters.AddWithValue("@MaintenanceType", model.MaintenanceType);
                sqlcomm.Parameters.AddWithValue("@MaintenanceCost", model.MaintenanceCost);
                sqlcomm.Parameters.AddWithValue("@MaintenanceDate", model.MaintenanceDate);
                sqlcomm.Parameters.AddWithValue("@Description", model.Description);
                sqlcomm.Parameters.AddWithValue("@Notes", model.Notes);
                sqlcomm.Parameters.AddWithValue("@IsCompleted", model.IsCompleted);
                sqlcomm.Parameters.AddWithValue("@MaintenanceID", model.MaintenanceID);

                db.ExecuteNonQuery(sqlcomm);
                sqlcomm.Parameters.Clear();
                return true;
            }
            catch (Exception ex)
            {
                throw new Exception("UpdateData() " + ex.Message);
            }
        }

        private string isValidate(VehicleMaintenanceModel model)
        {
            if (model.VehicleID == 0)
            {
                return "Please Select Vehicle";
            }
            if (model.MaintenanceType == "")
            {
                return "Please Type Maintenance Activity";
            }
            if (model.MaintenanceCost <= 0)
            {
                return "Please Enter Maintenance Cost";
            }
            if (model.Description == "")
            {
                return "Please Type Maintenance Description";
            }
            return null;
        }

        [HttpPost]
        public IActionResult deleteVehicleMaintenance(int MaintenanceID)
        {
            SqlCommand sqlcomm = new SqlCommand();
            sqlcomm.CommandText = "DELETE FROM MaintenanceActivities where MaintenanceID = " + MaintenanceID;
            db.ExecuteNonQuery(sqlcomm);
            return Json(new { success = true, message = "Vehicle Maintenance deleted successfully." });
        }

        public IActionResult GetMaintenanceRecordById(int id)
        {
            SqlCommand sqlcomm = new SqlCommand();
            sqlcomm.CommandText = "select VehicleID,MaintenanceType,MaintenanceDate,IsCompleted,MaintenanceCost,Description,Notes from MaintenanceActivities where MaintenanceID = " + id;
            DataTable dt = db.GetDataTable(sqlcomm);

            if (dt.Rows.Count == 0)
            {
                return Json(new { success = true, data = new List<object>() });
            }

            var records = dt.AsEnumerable().Select(row => new
            {
                VehicleID = row.Field<int>("VehicleID"),
                MaintenanceType = row.Field<string>("MaintenanceType"),
                IsCompleted = row.Field<bool>("IsCompleted"),
                MaintenanceCost = row.Field<decimal>("MaintenanceCost"),
                MaintenanceDate = row.Field<DateTime>("MaintenanceDate"),
                Description = row.Field<string>("Description"),
                Notes = row.Field<string>("Notes"),
            }).ToList();

            return Json(new { success = true, data = records });
        }
    }
}

NasrullahKhan_SkillTest_Truckoom/Views/VehicleMaintenance/Index.cshtml
@model VehicleMaintenanceModel
@{
    ViewData["Title"] = "Vehicle Maintenance";
}
<link rel="stylesheet" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css">
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
    <div class="panel panel-default" data-panel-close="false">
        <div class="panel-heading" id="divReportParmTitle"><span class="label label-primary" id="lblReportParmTitle"></span></div>
        <button class="btn btn-success pull-right" data-toggle="modal" data-target="#addVehicleMaintenanceModal" style="margin-top: -6px;">
            Add New Vehicle Maintenance
        </button>
        <div class="row">
            <div class="col-md-12">
                <div class="panel-body">
                    <div class="comment-box">
                        <div class="table-responsive">
                            <table class="table js-exportable table-hover dataTable no-footer" role="grid" id="VehicleMaintenanceTable">
                                <thead>
                                    <tr>
                                        <th>Sr#</th>
                                        <th>ID</th>
                                        <th>Make</th>
                                        <th>Model</th>
                                        <th>Year</th>
                                        <th>LicensePlate</th>
                                        <th>Type</th>
                                        <th>Date</th>
                                        <th>Description</th>
                                        <th>Notes</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>


                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addVehicleMaintenanceModal" tabindex="-1" role="dialog" aria-labelledby="addVehicleMaintenanceModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addVehicleMaintenanceModalLabel">Add New Vehicle Maintenance</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="vehicleMaintenanceForm">
                    <div class="form-group">
                        <label for="VehicleID">Vehicle</label>
                        @Html.DropDownListFor(modelItem => Model.VehicleID, (IEnumerable<SelectListItem>)ViewBag.Vehicle, new { @class = "form-control", @id = "VehicleID" })

                    </div>
                    <div class="form-group">
                        <label for="MaintenanceType">Maintenance Activity</label>
                        <input asp-for="MaintenanceID" type="text" class="form-control" id="MaintenanceType" name="MaintenanceType">
                    </div>
                    <div class="form-group">
                        <label for="date">Date</label>
                        <input asp-for="MaintenanceDate" type="date" class="form-control" id="date" name="MaintenanceDate" value="@DateTime.Now.ToString("dd-MM-yyyy")">
                    </div>
                    <div class="form-group">
                        <label>IsCompleted</label>
                        <input asp-for=IsCompleted type="checkbox" id="IsCompleted" />

                    </div>
                    <div class="form-group">
                        <label for="MaintenanceCost">MaintenanceCost</label>
                        <input asp-for="MaintenanceCost" type="number" class="form-control" id="MaintenanceCost" name="MaintenanceCost">
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea asp-for="Description" class="form-control" id="description" name="Description"></textarea>
                    </div>
                    <div class="form-group">
                        <label for="notes">Notes</label>
                        <textarea asp-for="Notes" class="form-control" id="notes" name="Notes"></textarea>
                    </div>
                    <button type="button" class="btn btn-primary" id="btnAddMaintenanceActivity">Save</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js"></script>

<script>
    let isEdit = false;

    $(function () {
        debugger;

        GetMaintenanceRecords();
        //$('#addVehicleMaintenanceModal').modal('show');
        $("#btnAddMaintenanceActivity").click(function (event) {
            event.preventDefault();

            debugger;

            var url = '@Url.Action("SaveVehicleMaintenance", "VehicleMaintenance")';
            var formdata = new FormData($('form')[0]);
            var MaintenanceID = $(this).attr("MaintenanceID");
            formdata.append('MaintenanceID', MaintenanceID);
            formdata.append('IsEdit', isEdit);

            $.ajax({
                type: "POST",
                url: url,
                data: formdata,
                processData: false,
                contentType: false,
                success: function (response) {
                    if (response.success) {
                        alert(response.responseText);
                        GetMaintenanceRecords();
                        ClearForm();
                    } else {
                        alert('Error saving vehicle maintenance');
                    }
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
            $('#addVehicleMaintenanceModal').modal('hide');
            return false;
        });
    });

    function GetMaintenanceRecords() {
        $.ajax({
            url: '@Url.Action("GetMaintenanceRecord", "VehicleMaintenance")',
            method: 'GET',
            dataType: 'json',
            success: function (response) {
                var tableBody = $('#VehicleMaintenanceTable tbody');
                tableBody.empty();
                console.log(response.data);
                if (response.success && response.data.length === 0) {
                    var noRecordsRow = `
                        <tr>
                            <td colspan="12" style="text-align:center;">No records found</td>
                        </tr>
                    `;
                    tableBody.append(noRecordsRow);
                } else {
                    $.each(response.data, function (index, record) {
                        var row = `
                            <tr>
                                <td>${index + 1}</td>
                                    <td>${record.maintenanceID}</td>
                                    <td>${record.make}</td>
                                    <td>${record.model}</td>
                                    <td>${record.year}</td>
                                    <td>${record.licensePlate}</td>
                                    <td>${record.maintenanceType}</td>
                                    <td>${new Date(record.maintenanceDate).toLocaleDateString()}</td>
                                    <td>${record.description}</td>
                                    <td>${record.notes}</td>
                                <td>
                                                        <button class="btn btn-primary btn-edit" onclick="editMaintenanceRecord(${record.maintenanceID})">Edit</button>
                                                <button class="btn btn-danger btn-delete" onclick="deleteVehicleMaintenance(${record.maintenanceID})">Delete</button>
                                </td>
                            </tr>
                        `;
                        tableBody.append(row);
                    });
                }

                $('#VehicleMaintenanceTable').DataTable();
            },
            error: function (error) {
                console.error('Error fetching data:', error);
            }
        });
    }

    function editMaintenanceRecord(maintenanceID) {
        $("#btnAddMaintenanceActivity").attr("MaintenanceID", maintenanceID);

        $.ajax({
            url: '@Url.Action("GetMaintenanceRecordById", "VehicleMaintenance")',
            method: 'GET',
            data: { id: maintenanceID },
            dataType: 'json',
            success: function (response) {
                if (response.success && response.data) {
                    var maintenance = response.data[0];
                    var formattedDate = new Date(maintenance.maintenanceDate).toISOString().split('T')[0];
                    console.log(maintenance);
                    $('#addVehicleMaintenanceModal').modal('show');

                    $('#VehicleID').val(maintenance.vehicleID);
                    $('#MaintenanceType').val(maintenance.maintenanceType);
                    $('#MaintenanceCost').val(maintenance.maintenanceCost);
                    $('#date').val(formattedDate);
                    $('#description').val(maintenance.description);
                    $('#notes').val(maintenance.notes);
                    $('#IsCompleted').prop('checked', maintenance.isCompleted);
                    isEdit = true;

                } else {
                    alert('Failed to load maintenance record.');
                }
            },
            error: function (error) {
                console.error('Error fetching maintenance record:', error);
            }
        });
    }


    function deleteVehicleMaintenance(maintenanceID) {
        debugger;
        if (confirm("Are you sure you want to delete this vehicle?")) {
            $.ajax({
                url: '@Url.Action("deleteVehicleMaintenance", "VehicleMaintenance")',
                method: 'POST',
                data: { MaintenanceID: maintenanceID },
                success: function (response) {
                    alert("Vehicle deleted successfully");
                    GetMaintenanceRecords();
                },
                error: function (error) {
                    console.error("Error deleting vehicle:", error);
                }
            });
        }
    }


    function ClearForm() {
        $('form')[0].reset();
        $("#VehicleID").val("");
        $('#VehicleID').trigger("chosen:updated");
        $('#MaintenanceType').val("");
        $('#date').val("");
        $('#MaintenanceCost').val("");
        $('#description').val("");
        $('#notes').val("");
        $('#IsCompleted').prop('checked', false);
        isEdit = false;
    }

</script>